### ISSUE TITLE
The item 'latte › xhtml' is deprecated

### ISSUE THREAD

**Issue by DEK-Pham-The-Anh** [contributte/starter-skeleton#261]
Wanted to start a webserver as described in `readme.md` but got this error caused by line 5 in
`\vendor\nette\application\src\Bridges\ApplicationDI\LatteExtension.php`:
```
public function getConfigSchema(): Nette\Schema\Schema
{
  return Expect::structure([
    'debugger' => Expect::anyOf(true, false, 'all'),
    'xhtml' => Expect::bool(false)->deprecated(),
    'macros' => Expect::arrayOf('string'),
    'templateClass' => Expect::string(),
    'strictTypes' => Expect::bool(false),
  ]);
}
```

Why is it marked as deprecated? Works only if removed `->deprecated()` ...

**Comment by f3l1x** [comment]
Should be fixed. Thanks for report.
